# Generated by Django 5.2 on 2026-06-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_alter_userpermissionoverride_permission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermissionOverride',
        ),
    ]
