import React from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";

const hookState = vi.hoisted(() => ({
  payrolls: [],
  workers: [],
  projects: [],
  loading: false,
  error: null,
  fetchPayrolls: vi.fn(),
  fetchWorkers: vi.fn(),
  fetchProjects: vi.fn(),
  fetchDailyStatus: vi.fn(),
  createPayroll: vi.fn(),
  updatePayroll: vi.fn(),
  deletePayroll: vi.fn(),
  generatePayrolls: vi.fn(),
  approvePayroll: vi.fn(),
  markPayrollPaid: vi.fn(),
}));

const authState = vi.hoisted(() => ({
  permissions: [
    "daily_worker_payroll.create",
    "daily_worker_payroll.update",
    "daily_worker_payroll.delete",
  ],
}));

const langState = vi.hoisted(() => ({
  language: "en",
}));

const translate = vi.hoisted(() => (key, params) =>
  ({
    "WorkerPayrollManager.title": "Worker Payroll",
    "WorkerPayrollManager.addPayroll": "Add Payroll",
    "WorkerPayrollManager.autoGeneratePayroll": "Auto generate payroll",
    "WorkerPayrollManager.autoGenerateDescription": "Generate payroll from attendance",
    "WorkerPayrollManager.periodStart": "Period start",
    "WorkerPayrollManager.periodEnd": "Period end",
    "WorkerPayrollManager.defaultMethod": "Default method",
    "WorkerPayrollManager.cashOnSite": "Cash on site",
    "WorkerPayrollManager.bankTransfer": "Bank transfer",
    "WorkerPayrollManager.mobileMoney": "Mobile money",
    "WorkerPayrollManager.generating": "Generating",
    "WorkerPayrollManager.validatingAttendance": "Checking attendance",
    "WorkerPayrollManager.generatePayroll": "Generate payroll",
    "WorkerPayrollManager.generatedPayrollHistory": "Generated payroll history",
    "WorkerPayrollManager.worker": "Worker",
    "WorkerPayrollManager.period": "Period",
    "WorkerPayrollManager.daysWorked": "Days worked",
    "WorkerPayrollManager.grossNet": "Gross / net",
    "WorkerPayrollManager.status": "Status",
    "WorkerPayrollManager.actions": "Actions",
    "WorkerPayrollManager.noPayrolls": "No payrolls",
    "WorkerPayrollManager.days": "days",
    "WorkerPayrollManager.overtime": "overtime",
    "WorkerPayrollManager.deductions": "Deductions",
    "WorkerPayrollManager.paidOn": "Paid on",
    "WorkerPayrollManager.modal.draft": "Draft",
    "WorkerPayrollManager.modal.approved": "Approved",
    "WorkerPayrollManager.modal.paid": "Paid",
    "WorkerPayrollManager.approve": "Approve",
    "WorkerPayrollManager.markPaid": "Mark paid",
    "WorkerPayrollManager.editPayroll": "Edit payroll",
    "WorkerPayrollManager.deletePayroll": "Delete payroll",
    "WorkerPayrollManager.deleteConfirmation": `Delete ${params?.name || ""}?`,
    "WorkerPayrollManager.confirmPayment": "Confirm payment",
    "WorkerPayrollManager.selectDateRange": "Select date range",
    "WorkerPayrollManager.invalidDateRange": "Period end must be on or after period start",
    "WorkerPayrollManager.attendanceValidationTitle": "Attendance required before payroll",
    "WorkerPayrollManager.attendanceMissingSingle": "Attendance has not been recorded for this date. Please take attendance before generating payroll.",
    "WorkerPayrollManager.attendanceMissingMultiple": "Payroll cannot be generated because attendance is missing for the following dates:",
    "WorkerPayrollManager.attendanceMissingInstruction": "Please record attendance for these dates before generating payroll.",
    "WorkerPayrollManager.missingAttendanceDates": "Missing attendance dates",
    "WorkerPayrollManager.goToAttendance": "Go to attendance",
    "WorkerPayrollManager.couldNotDeletePayroll": "Could not delete payroll",
    "WorkerPayrollManager.modal.editPayroll": "Edit Payroll",
    "WorkerPayrollManager.modal.addPayroll": "Add Payroll",
    "WorkerPayrollManager.modal.close": "Close",
    "WorkerPayrollManager.modal.worker": "Worker",
    "WorkerPayrollManager.modal.selectWorker": "Select worker",
    "WorkerPayrollManager.modal.project": "Project",
    "WorkerPayrollManager.modal.noProject": "No project",
    "WorkerPayrollManager.modal.periodStart": "Period start",
    "WorkerPayrollManager.modal.periodEnd": "Period end",
    "WorkerPayrollManager.modal.dailyRate": "Daily rate",
    "WorkerPayrollManager.modal.overtimeRate": "Overtime rate",
    "WorkerPayrollManager.modal.deductions": "Deductions",
    "WorkerPayrollManager.modal.status": "Status",
    "WorkerPayrollManager.modal.paymentMethod": "Payment method",
    "WorkerPayrollManager.modal.cash": "Cash",
    "WorkerPayrollManager.modal.bankTransfer": "Bank transfer",
    "WorkerPayrollManager.modal.mobileMoney": "Mobile money",
    "WorkerPayrollManager.modal.check": "Check",
    "WorkerPayrollManager.modal.paymentDate": "Payment date",
    "WorkerPayrollManager.modal.notes": "Notes",
    "WorkerPayrollManager.modal.cancel": "Cancel",
    "WorkerPayrollManager.modal.saving": "Saving",
    "WorkerPayrollManager.modal.savePayroll": "Save payroll",
    "WorkerPayrollManager.modal.errorMessage": "Could not save payroll",
    to: "to",
  })[key] || key,
);

const toast = vi.hoisted(() => ({
  success: vi.fn(),
  error: vi.fn(),
}));

vi.mock("../../hooks/useDailyWorkers", () => ({
  useDailyWorkers: () => ({
    fetchPayrolls: hookState.fetchPayrolls,
    fetchWorkers: hookState.fetchWorkers,
    fetchProjects: hookState.fetchProjects,
    fetchDailyStatus: hookState.fetchDailyStatus,
    createPayroll: hookState.createPayroll,
    updatePayroll: hookState.updatePayroll,
    deletePayroll: hookState.deletePayroll,
    generatePayrolls: hookState.generatePayrolls,
    approvePayroll: hookState.approvePayroll,
    markPayrollPaid: hookState.markPayrollPaid,
    loading: hookState.loading,
    error: hookState.error,
  }),
}));

vi.mock("../../hooks/useLanguage", () => ({
  useLanguage: () => ({ t: translate, language: langState.language }),
}));

vi.mock("../../hooks/useCalendar", () => ({
  useCalendar: () => ({
    calendar: "gregorian",
    formatDate: (value) => value || "",
    formatDateTime: (value) => value || "",
  }),
}));

vi.mock("../../auth/AuthContext", () => ({
  useAuth: () => ({ permissions: authState.permissions }),
}));

vi.mock("react-hot-toast", () => ({
  default: toast,
}));

import WorkerPayrollManager from "./WorkerPayrollManager";

const payrolls = [
  {
    id: 1,
    worker: 10,
    worker_name: "Nadia Worker",
    worker_id_code: "DW-10",
    project: 4,
    period_start: "2026-01-01",
    period_end: "2026-01-15",
    total_days_worked: 12,
    total_overtime_hours: 4,
    gross_amount: "1200.00",
    net_pay: "1193.00",
    advances: "5",
    deductions: "2",
    currency: "AFN",
    status: "draft",
    is_paid: false,
    payment_method: "cash",
    payment_date: "",
    notes: "site work",
  },
  {
    id: 2,
    worker: 11,
    worker_name: "Omar Paid",
    worker_id_code: "DW-11",
    period_start: "2026-01-01",
    period_end: "2026-01-15",
    total_days_worked: 14,
    total_overtime_hours: 0,
    gross_amount: "1400.00",
    net_pay: "1400.00",
    advances: "0",
    deductions: "0",
    currency: "USD",
    status: "approved",
    is_paid: true,
    payment_date: "2026-01-20",
  },
];

const workers = [
  {
    id: 10,
    full_name: "Nadia Worker",
    daily_rate: "100",
    overtime_hourly_rate: "12.50",
    currency: "AFN",
  },
  {
    id: 11,
    full_name: "Omar Paid",
    daily_rate: "150",
    overtime_hourly_rate: "15",
    currency: "USD",
  },
];

const projects = [
  { id: 4, name: "Tower" },
  { id: 5, name: "Bridge" },
];

async function renderLoaded(props = {}) {
  render(<WorkerPayrollManager {...props} />);
  expect(await screen.findByText("Worker Payroll")).toBeInTheDocument();
}

function setSuccessfulHookDefaults() {
  hookState.fetchPayrolls = vi.fn(() => Promise.resolve(hookState.payrolls));
  hookState.fetchWorkers = vi.fn(() => Promise.resolve(hookState.workers));
  hookState.fetchProjects = vi.fn(() => Promise.resolve(hookState.projects));
  hookState.fetchDailyStatus = vi.fn(() => Promise.resolve({ marked_records: [{ id: 1 }] }));
  hookState.createPayroll = vi.fn(() => Promise.resolve({ id: 99 }));
  hookState.updatePayroll = vi.fn(() => Promise.resolve({ id: 1 }));
  hookState.deletePayroll = vi.fn(() => Promise.resolve());
  hookState.generatePayrolls = vi.fn(() => Promise.resolve({ message: "Generated 2 payrolls." }));
  hookState.approvePayroll = vi.fn(() => Promise.resolve({ id: 1 }));
  hookState.markPayrollPaid = vi.fn(() => Promise.resolve({ id: 1 }));
}

describe("WorkerPayrollManager", () => {
  beforeEach(() => {
    cleanup();
    vi.clearAllMocks();
    hookState.payrolls = payrolls;
    hookState.workers = workers;
    hookState.projects = projects;
    hookState.loading = false;
    hookState.error = null;
    authState.permissions = [
      "daily_worker_payroll.create",
      "daily_worker_payroll.update",
      "daily_worker_payroll.delete",
    ];
    langState.language = "en";
    setSuccessfulHookDefaults();
  });

  it("loads payrolls, workers, projects, totals, deductions, statuses, and management actions", async () => {
    await renderLoaded();

    expect(hookState.fetchPayrolls).toHaveBeenCalled();
    expect(hookState.fetchWorkers).toHaveBeenCalledWith({ status: "active" });
    expect(hookState.fetchProjects).toHaveBeenCalled();
    expect(screen.getAllByText("Nadia Worker").length).toBeGreaterThan(0);
    expect(screen.getAllByText("DW-10").length).toBeGreaterThan(0);
    expect(screen.getAllByText("1193.00 AFN").length).toBeGreaterThan(0);
    expect(screen.getByText("Deductions: 7.00")).toBeInTheDocument();
    expect(screen.getAllByText("Draft").length).toBeGreaterThan(0);
    expect(screen.getAllByText("Paid on 2026-01-20").length).toBeGreaterThan(0);
    expect(screen.getAllByRole("button", { name: "Approve" }).length).toBeGreaterThan(0);
    expect(screen.getAllByRole("button", { name: "Mark paid" }).length).toBeGreaterThan(0);
    expect(screen.getAllByRole("button", { name: "Edit payroll" }).length).toBeGreaterThan(0);
    expect(screen.getAllByRole("button", { name: "Delete payroll" }).length).toBeGreaterThan(0);
  });

  it("generates payrolls with validation, project filtering, payment method, and hidden create controls", async () => {
    await renderLoaded();

    fireEvent.submit(screen.getByText("Auto generate payroll").closest("div").querySelector("form"));
    expect(toast.error).toHaveBeenCalledWith("Select date range");

    fireEvent.change(screen.getByLabelText("Period start"), { target: { value: "2026-02-01" } });
    fireEvent.change(screen.getByLabelText("Period end"), { target: { value: "2026-02-15" } });
    fireEvent.change(screen.getByDisplayValue("Cash on site"), {
      target: { value: "bank_transfer" },
    });
    fireEvent.change(screen.getByDisplayValue("General / no project"), {
      target: { value: "4" },
    });
    await act(async () => {
      fireEvent.click(screen.getByRole("button", { name: "Generate payroll" }));
    });

    expect(hookState.generatePayrolls).toHaveBeenCalledWith({
      period_start: "2026-02-01",
      period_end: "2026-02-15",
      payment_method: "bank_transfer",
      project: "4",
    });
    expect(toast.success).toHaveBeenCalledWith("Generated 2 payrolls.");

    hookState.generatePayrolls = vi.fn(() => Promise.reject(new Error("generate failed")));
    fireEvent.change(screen.getByDisplayValue("Tower"), { target: { value: "" } });
    await act(async () => {
      fireEvent.click(screen.getByRole("button", { name: "Generate payroll" }));
    });
    expect(hookState.generatePayrolls).toHaveBeenCalledWith(
      expect.objectContaining({ project: null }),
    );

    cleanup();
    authState.permissions = [];
    hookState.payrolls = [];
    render(<WorkerPayrollManager />);
    expect((await screen.findAllByText("No payrolls")).length).toBeGreaterThan(0);
    expect(screen.queryByRole("button", { name: "Add Payroll" })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Generate payroll" })).not.toBeInTheDocument();
  });

  it("blocks payroll generation and lists dates when attendance is missing", async () => {
    const onOpenAttendance = vi.fn();
    hookState.fetchDailyStatus = vi.fn((date) =>
      Promise.resolve({
        marked_records:
          date === "2026-08-06" || date === "2026-08-07" ? [{ id: date }] : [],
      }),
    );
    await renderLoaded({ onOpenAttendance });

    fireEvent.change(screen.getByLabelText("Period start"), {
      target: { value: "2026-08-05" },
    });
    fireEvent.change(screen.getByLabelText("Period end"), {
      target: { value: "2026-08-08" },
    });

    await act(async () => {
      fireEvent.click(screen.getByRole("button", { name: "Generate payroll" }));
    });

    expect(hookState.fetchDailyStatus).toHaveBeenCalledTimes(4);
    expect(hookState.generatePayrolls).not.toHaveBeenCalled();
    expect(
      screen.getByRole("heading", { name: "Attendance required before payroll" }),
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        "Attendance has not been recorded for 2026-08-05. Please complete attendance before generating payroll.",
      ),
    ).toBeInTheDocument();
    expect(screen.getByText("2026-08-05")).toBeInTheDocument();
    expect(screen.getByText("2026-08-08")).toBeInTheDocument();
    expect(screen.queryByText("2026-08-06")).not.toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Go to attendance" }));
    expect(onOpenAttendance).toHaveBeenCalled();
    await waitFor(() =>
      expect(
        screen.queryByRole("heading", { name: "Attendance required before payroll" }),
      ).not.toBeInTheDocument(),
    );
  });

  it("skips non-working days during attendance validation", async () => {
    hookState.fetchDailyStatus = vi.fn((date) =>
      Promise.resolve({
        marked_records: date === "2026-08-06" ? [{ id: date }] : [],
        work_calendar: {
          is_working_day: date !== "2026-08-05",
          day_type: date === "2026-08-05" ? "official_holiday" : "working_day",
        },
      }),
    );
    await renderLoaded();

    fireEvent.change(screen.getByLabelText("Period start"), {
      target: { value: "2026-08-05" },
    });
    fireEvent.change(screen.getByLabelText("Period end"), {
      target: { value: "2026-08-06" },
    });

    await act(async () => {
      fireEvent.click(screen.getByRole("button", { name: "Generate payroll" }));
    });

    expect(hookState.fetchDailyStatus).toHaveBeenCalledTimes(2);
    expect(hookState.generatePayrolls).toHaveBeenCalledWith(
      expect.objectContaining({
        period_start: "2026-08-05",
        period_end: "2026-08-06",
      }),
    );
    expect(
      screen.queryByRole("heading", { name: "Attendance required before payroll" }),
    ).not.toBeInTheDocument();
  });

  it("creates payrolls from the modal and fills rates from the selected worker", async () => {
    await renderLoaded();

    fireEvent.click(screen.getByRole("button", { name: "Add Payroll" }));
    const dialog = screen.getByRole("heading", { name: "Add Payroll" }).closest("div").parentElement;

    fireEvent.change(within(dialog).getByLabelText("Worker"), { target: { value: "10" } });
    expect(within(dialog).getByLabelText("Daily rate")).toHaveValue(100);
    expect(within(dialog).getByLabelText("Overtime rate")).toHaveValue(12.5);
    fireEvent.change(within(dialog).getByLabelText("Project"), { target: { value: "4" } });
    fireEvent.change(within(dialog).getByLabelText("Period start"), {
      target: { value: "2026-03-01" },
    });
    fireEvent.change(within(dialog).getByLabelText("Period end"), {
      target: { value: "2026-03-15" },
    });
    fireEvent.change(within(dialog).getByLabelText("Deductions"), { target: { value: "3" } });
    fireEvent.change(within(dialog).getByLabelText("Status"), { target: { value: "approved" } });
    fireEvent.change(within(dialog).getByLabelText("Payment method"), {
      target: { value: "mobile_money" },
    });
    fireEvent.change(within(dialog).getByLabelText("Payment date"), {
      target: { value: "2026-03-20" },
    });
    fireEvent.change(within(dialog).getByLabelText("Notes"), { target: { value: "manual" } });

    await act(async () => {
      fireEvent.click(within(dialog).getByRole("button", { name: "Save payroll" }));
    });

    expect(hookState.createPayroll).toHaveBeenCalledWith(
      expect.objectContaining({
        worker: "10",
        project: "4",
        daily_rate_applied: "100",
        overtime_rate_applied: "12.50",
        deductions: "3",
        status: "approved",
        payment_method: "mobile_money",
        payment_date: "2026-03-20",
        notes: "manual",
      }),
    );
    expect(toast.success).toHaveBeenCalledWith("Payroll created.");
  });

  it("shows modal save errors, closes without saving, edits payrolls, and resets blank optional fields", async () => {
    await renderLoaded();

    hookState.createPayroll = vi.fn(() =>
      Promise.reject({ response: { data: { detail: "Create denied." } } }),
    );
    fireEvent.click(screen.getByRole("button", { name: "Add Payroll" }));
    let dialog = screen.getByRole("heading", { name: "Add Payroll" }).closest("div").parentElement;
    fireEvent.change(within(dialog).getByLabelText("Worker"), { target: { value: "11" } });
    fireEvent.change(within(dialog).getByLabelText("Period start"), {
      target: { value: "2026-04-01" },
    });
    fireEvent.change(within(dialog).getByLabelText("Period end"), {
      target: { value: "2026-04-15" },
    });
    await act(async () => {
      fireEvent.click(within(dialog).getByRole("button", { name: "Save payroll" }));
    });
    expect(await within(dialog).findByText("Create denied.")).toBeInTheDocument();
    fireEvent.click(within(dialog).getByRole("button", { name: "Close" }));
    expect(screen.queryByRole("heading", { name: "Add Payroll" })).not.toBeInTheDocument();

    fireEvent.click(screen.getAllByRole("button", { name: "Edit payroll" })[0]);
    dialog = screen.getByRole("heading", { name: "Edit Payroll" }).closest("div").parentElement;
    expect(within(dialog).getByLabelText("Worker")).toBeDisabled();
    fireEvent.change(within(dialog).getByLabelText("Project"), { target: { value: "" } });
    fireEvent.change(within(dialog).getByLabelText("Payment date"), { target: { value: "" } });
    fireEvent.change(within(dialog).getByLabelText("Daily rate"), { target: { value: "" } });
    fireEvent.change(within(dialog).getByLabelText("Overtime rate"), { target: { value: "" } });
    await act(async () => {
      fireEvent.click(within(dialog).getByRole("button", { name: "Save payroll" }));
    });
    expect(hookState.updatePayroll).toHaveBeenCalledWith(
      1,
      expect.objectContaining({
        project: null,
        payment_date: null,
        daily_rate_applied: undefined,
        overtime_rate_applied: undefined,
      }),
    );
    expect(toast.success).toHaveBeenCalledWith("Payroll updated.");
  });

  it("approves, marks paid, deletes, and reports delete failures", async () => {
    await renderLoaded();

    const approveButtons = await screen.findAllByRole("button", { name: "Approve" });
    await act(async () => {
      fireEvent.click(approveButtons[0]);
    });
    expect(hookState.approvePayroll).toHaveBeenCalledWith(1);
    expect(toast.success).toHaveBeenCalledWith("Payroll approved.");

    fireEvent.click(screen.getAllByRole("button", { name: "Mark paid" })[0]);
    expect(screen.getByRole("heading", { name: "Mark payroll paid" })).toBeInTheDocument();
    const markPaidDialog = screen
      .getByRole("heading", { name: "Mark payroll paid" })
      .closest("div").parentElement;
    await act(async () => {
      fireEvent.click(within(markPaidDialog).getByRole("button", { name: "Mark paid" }));
    });
    expect(hookState.markPayrollPaid).toHaveBeenCalledWith(
      1,
      expect.stringMatching(/^\d{4}-\d{2}-\d{2}$/),
    );
    expect(toast.success).toHaveBeenCalledWith("Payroll marked as paid.");

    fireEvent.click(screen.getAllByRole("button", { name: "Delete payroll" })[0]);
    expect(screen.getByText("Delete Nadia Worker?")).toBeInTheDocument();
    await act(async () => {
      fireEvent.click(screen.getByRole("button", { name: "Delete" }));
    });
    expect(hookState.deletePayroll).toHaveBeenCalledWith(1);
    expect(toast.success).toHaveBeenCalledWith("Payroll deleted.");

    hookState.deletePayroll = vi.fn(() => Promise.reject(new Error("delete failed")));
    fireEvent.click(screen.getAllByRole("button", { name: "Delete payroll" })[0]);
    await act(async () => {
      fireEvent.click(screen.getByRole("button", { name: "Delete" }));
    });
    expect(toast.error).toHaveBeenCalledWith("Could not delete payroll");
  });

  it("swallows centrally handled load and action failures while rendering hook errors and RTL state", async () => {
    hookState.fetchPayrolls = vi.fn(() => Promise.reject(new Error("load payrolls")));
    hookState.fetchWorkers = vi.fn(() => Promise.reject(new Error("load workers")));
    hookState.error = "Central hook error";
    hookState.loading = true;
    langState.language = "fa";

    render(<WorkerPayrollManager />);

    expect(await screen.findByText("Worker Payroll")).toBeInTheDocument();
    expect(document.querySelector("[dir='rtl']")).toBeInTheDocument();
    expect(screen.getByText("Central hook error")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Generating" })).toBeDisabled();
    expect(screen.getAllByText("No payrolls").length).toBeGreaterThan(0);

    hookState.loading = false;
    hookState.payrolls = payrolls;
    hookState.approvePayroll = vi.fn(() => Promise.reject(new Error("approve failed")));
    hookState.markPayrollPaid = vi.fn(() => Promise.reject(new Error("paid failed")));
    setSuccessfulHookDefaults();
  });
});
