# Generated by Django 5.2 on 2026-07-08 00:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=200)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('overtime_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('AFN', 'Afghani (AFN)'), ('USD', 'US Dollar (USD)')], default='AFN', max_length=3)),
                ('skill_type', models.CharField(choices=[('mason', 'Mason'), ('carpenter', 'Carpenter'), ('electrician', 'Electrician'), ('painter', 'Painter'), ('plumber', 'Plumber'), ('steel_fixer', 'Steel Fixer'), ('driver', 'Driver'), ('excavator_operator', 'Excavator Operator'), ('helper', 'Helper'), ('other', 'Other')], default='helper', max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('joining_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_daily_workers', to='project.project')),
            ],
            options={
                'verbose_name': 'Daily Worker',
                'verbose_name_plural': 'Daily Workers',
                'ordering': ['-joining_date', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('AFN', 'Afghani (AFN)'), ('USD', 'US Dollar (USD)')], default='AFN', max_length=3)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_worker_advances', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='labour.dailyworker')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('overtime', 'Overtime')], default='present', max_length=20)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_worker_attendance', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_attendances', to='project.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='labour.dailyworker')),
            ],
            options={
                'verbose_name': 'Worker Attendance',
                'verbose_name_plural': 'Worker Attendance Records',
                'ordering': ['-date', 'worker__full_name'],
                'unique_together': {('worker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkerPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('present_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('half_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('absent_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('daily_rate_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_rate_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('AFN', 'Afghani (AFN)'), ('USD', 'US Dollar (USD)')], default='AFN', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('check', 'Check')], default='cash', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_worker_payrolls', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_payrolls', to='project.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='labour.dailyworker')),
            ],
            options={
                'ordering': ['-period_start', 'worker__full_name'],
                'unique_together': {('worker', 'project', 'period_start', 'period_end')},
            },
        ),
    ]
