# Generated by Django 5.2 on 2026-06-20 14:27

import django.core.validators
import django.db.models.deletion
import subcontractor.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('scope_of_work', models.TextField(blank=True, default='')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('retention_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('retention_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_contracts', to='project.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('signed_contract', 'Signed Contract'), ('boq', 'BOQ File'), ('drawing', 'Drawing'), ('invoice', 'Invoice'), ('quotation', 'Quotation'), ('supporting', 'Supporting Document')], default='supporting', max_length=30)),
                ('file', models.FileField(upload_to=subcontractor.models.contract_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='subcontractor.contract')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('advance', 'Advance'), ('progress', 'Progress'), ('retention_release', 'Retention Release'), ('final', 'Final'), ('other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subcontractor.contract')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('tax_number', models.CharField(blank=True, default='', max_length=100)),
                ('registration_number', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('specialization', models.CharField(choices=[('concrete', 'Concrete'), ('steel', 'Steel'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('finishing', 'Finishing'), ('excavation', 'Excavation'), ('hvac', 'HVAC'), ('landscaping', 'Landscaping'), ('other', 'Other')], db_index=True, max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'specialization'], name='subcontract_name_cad5b4_idx'), models.Index(fields=['is_active'], name='subcontract_is_acti_167b59_idx')],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='subcontractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='subcontractor.subcontractor'),
        ),
        migrations.CreateModel(
            name='ContractVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_number', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount_change', models.DecimalField(decimal_places=2, max_digits=15)),
                ('days_added', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='subcontractor.contract')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['contract', 'approved'], name='subcontract_contrac_bc41eb_idx')],
                'unique_together': {('contract', 'variation_number')},
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='subcontract_contrac_3e384c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='subcontract_status_cea0db_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['project', 'status'], name='subcontract_project_b74de0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['subcontractor', 'status'], name='subcontract_subcont_f12934_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date', 'end_date'], name='subcontract_start_d_ff49ca_idx'),
        ),
    ]
