# Generated by Django 5.2 on 2026-06-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractor', '0002_alter_contract_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('AFN', 'Afghan Afghani'), ('USD', 'US Dollar')], db_index=True, default='AFN', max_length=3),
        ),
    ]
