# Generated by Django 5.2 on 2026-06-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractor', '0003_contract_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractvariation',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='contractvariation',
            name='subcontract_contrac_bc41eb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contractvariation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contractvariation',
            name='variation_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
