# Generated by Django 5.2 on 2026-06-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractor', '0005_contractinvoice_contractinvoicedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractinvoice',
            name='invoice_number',
            field=models.CharField(db_index=True, editable=False, max_length=100),
        ),
    ]
