# Generated by Django 5.2 on 2026-07-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcontractor', '0006_alter_contractinvoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractor',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
