# Generated by Codex on 2026-08-12

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subcontractor", "0007_alter_subcontractor_registration_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="contract_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                ],
            ),
        ),
    ]
