export const REPORTS = {
  projects: {
    key: "projects",
    label: "Projects",
    endpoint: "reports/projects/",
    description: "Budget, spending, contract exposure, and project status",
    filters: [
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "", label: "All Statuses" },
          { value: "planning", label: "Planning" },
          { value: "ongoing", label: "Ongoing" },
          { value: "completed", label: "Completed" },
          { value: "on_hold", label: "On Hold" },
        ],
      },
      {
        name: "property_type",
        label: "Property Type",
        type: "select",
        options: [
          { value: "", label: "All Types" },
          { value: "residential", label: "Residential" },
          { value: "commercial", label: "Commercial" },
          { value: "mixed", label: "Mixed Use" },
        ],
      },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
    ],
    columns: [
      { key: "name", label: "Project" },
      { key: "property_type", label: "Type" },
      { key: "location", label: "Location" },
      { key: "status", label: "Status", type: "badge" },
      { key: "total_floors", label: "Floors", type: "number" },
      { key: "estimated_budget", label: "Budget", type: "currency" },
      { key: "budget_currency", label: "Budget Cur" },
      { key: "expenses_usd", label: "Expenses USD", type: "currency" },
      { key: "expenses_afn", label: "Expenses AFN", type: "currency" },
      { key: "contracts_usd", label: "Contract Paid USD", type: "currency" },
      { key: "contracts_afn", label: "Contract Paid AFN", type: "currency" },
      { key: "worker_payroll_usd", label: "Worker Payroll USD", type: "currency" },
      { key: "worker_payroll_afn", label: "Worker Payroll AFN", type: "currency" },
      { key: "total_spent_usd", label: "Total USD", type: "currency" },
      { key: "total_spent_afn", label: "Total AFN", type: "currency" },
      { key: "expense_count", label: "Expenses", type: "number" },
    ],
  },

  expenses: {
    key: "expenses",
    label: "Expenses",
    endpoint: "reports/expenses/",
    description: "Expense totals, category mix, and monthly spending trend",
    filters: [
      { name: "project_id", label: "Project ID", type: "number" },
      {
        name: "expense_type",
        label: "Expense Type",
        type: "select",
        options: [
          { value: "", label: "All Types" },
          { value: "general", label: "General" },
          { value: "material", label: "Material" },
          { value: "construction", label: "Construction" },
          { value: "staff_salary", label: "Staff Salary" },
          { value: "daily_wage", label: "Daily Wage" },
          { value: "contract_payment", label: "Contract Payment" },
          { value: "equipment", label: "Equipment" },
          { value: "utility", label: "Utility" },
          { value: "other", label: "Other" },
        ],
      },
      {
        name: "status",
        label: "Approval Status",
        type: "select",
        options: [
          { value: "", label: "Approved Only" },
          { value: "approved", label: "Approved" },
          { value: "pending", label: "Pending" },
          { value: "rejected", label: "Rejected" },
        ],
      },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
    ],
    columns: [
      { key: "serial_number", label: "S/N" },
      { key: "project_id", label: "Project ID", type: "number" },
      { key: "expense_date", label: "Date", type: "date" },
      { key: "expense_type", label: "Type", type: "badge" },
      { key: "approval_status", label: "Approval", type: "badge" },
      { key: "amount_afn", label: "AFN", type: "number" },
      { key: "amount_usd", label: "USD", type: "number" },
    ],
  },

  payroll: {
    key: "payroll",
    label: "Payroll",
    endpoint: "reports/payroll/",
    description: "Employee and daily worker payroll totals, deductions, tax, and net payouts",
    filters: [
      {
        name: "source_type",
        label: "Source",
        type: "select",
        options: [
          { value: "", label: "Employees + Daily Workers" },
          { value: "employee", label: "Employees Only" },
          { value: "daily_worker", label: "Daily Workers Only" },
        ],
      },
      { name: "employee_id", label: "Employee ID", type: "number" },
      {
        name: "currency",
        label: "Currency",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "AFN", label: "AFN" },
          { value: "USD", label: "USD" },
        ],
      },
      {
        name: "payment_method",
        label: "Payment Method",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "bank_transfer", label: "Bank Transfer" },
          { value: "check", label: "Check" },
          { value: "cash", label: "Cash" },
          { value: "mobile_money", label: "Mobile Money" },
        ],
      },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
    ],
    columns: [
      { key: "source_type", label: "Source", type: "badge" },
      { key: "employee", label: "Person" },
      { key: "employee_id", label: "ID" },
      { key: "project", label: "Project" },
      { key: "department", label: "Dept / Skill" },
      { key: "period_start", label: "From", type: "date" },
      { key: "period_end", label: "To", type: "date" },
      { key: "currency", label: "Cur" },
      { key: "basic_salary", label: "Salary", type: "number" },
      { key: "daily_rate", label: "Daily Rate", type: "number" },
      { key: "overtime_hours", label: "OT Hrs", type: "number" },
      { key: "overtime_amount", label: "Overtime", type: "number" },
      { key: "bonus", label: "Bonus", type: "number" },
      { key: "advances", label: "Advances", type: "number" },
      { key: "gross_pay", label: "Gross", type: "number" },
      { key: "deductions", label: "Deduct", type: "number" },
      { key: "tax_deducted", label: "Tax", type: "number" },
      { key: "net_pay", label: "Net", type: "number" },
      { key: "status", label: "Status", type: "badge" },
    ],
  },

  attendance: {
    key: "attendance",
    label: "Attendance",
    endpoint: "reports/attendance/",
    description: "Employee and daily worker attendance status, project coverage, and overtime",
    filters: [
      {
        name: "source_type",
        label: "Source",
        type: "select",
        options: [
          { value: "", label: "Employees + Daily Workers" },
          { value: "employee", label: "Employees Only" },
          { value: "daily_worker", label: "Daily Workers Only" },
        ],
      },
      { name: "employee_id", label: "Employee ID", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "present", label: "Present" },
          { value: "absent", label: "Absent" },
          { value: "half_day", label: "Half Day" },
          { value: "leave", label: "Leave" },
          { value: "overtime", label: "Overtime" },
        ],
      },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
    ],
    columns: [
      { key: "source_type", label: "Source", type: "badge" },
      { key: "employee", label: "Person" },
      { key: "employee_id", label: "ID" },
      { key: "project", label: "Project" },
      { key: "date", label: "Date", type: "date" },
      { key: "status", label: "Status", type: "badge" },
      { key: "check_in", label: "In" },
      { key: "check_out", label: "Out" },
      { key: "overtime_hours", label: "OT Hrs", type: "number" },
      { key: "note", label: "Note" },
    ],
  },

  employees: {
    key: "employees",
    label: "Employees",
    endpoint: "reports/employees/",
    description: "Workforce size, salary concentration, and department mix",
    filters: [
      {
        name: "department",
        label: "Department",
        type: "select",
        options: [
          { value: "", label: "All Departments" },
          { value: "management", label: "Management" },
          { value: "engineering", label: "Engineering" },
          { value: "construction", label: "Construction" },
          { value: "administration", label: "Administration" },
          { value: "finance", label: "Finance" },
          { value: "hr", label: "Human Resources" },
          { value: "procurement", label: "Procurement" },
          { value: "safety", label: "Safety" },
        ],
      },
      {
        name: "employment_type",
        label: "Employment Type",
        type: "select",
        options: [
          { value: "", label: "All Types" },
          { value: "full_time", label: "Full Time" },
          { value: "part_time", label: "Part Time" },
          { value: "contract", label: "Contract" },
          { value: "temporary", label: "Temporary" },
        ],
      },
      {
        name: "is_active",
        label: "Active Status",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "true", label: "Active" },
          { value: "false", label: "Inactive" },
        ],
      },
    ],
    columns: [
      { key: "employee_id", label: "ID" },
      { key: "full_name", label: "Name" },
      { key: "department", label: "Dept" },
      { key: "position", label: "Position" },
      { key: "employment_type", label: "Type" },
      { key: "hire_date", label: "Hired", type: "date" },
      { key: "salary", label: "Salary", type: "number" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "is_active", label: "Active", type: "bool" },
    ],
  },

  contracts: {
    key: "contracts",
    label: "Contracts",
    endpoint: "reports/contracts/",
    description: "Contract value, payment progress, and currency exposure",
    filters: [
      { name: "project_id", label: "Project ID", type: "number" },
      { name: "subcontractor_id", label: "Subcontractor ID", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "draft", label: "Draft" },
          { value: "active", label: "Active" },
          { value: "completed", label: "Completed" },
          { value: "terminated", label: "Terminated" },
          { value: "cancelled", label: "Cancelled" },
        ],
      },
      {
        name: "currency",
        label: "Currency",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "AFN", label: "AFN" },
          { value: "USD", label: "USD" },
        ],
      },
    ],
    columns: [
      { key: "contract_number", label: "Contract #" },
      { key: "title", label: "Title" },
      { key: "project", label: "Project" },
      { key: "subcontractor", label: "Subcontractor" },
      { key: "currency", label: "Cur" },
      { key: "contract_value", label: "Value", type: "number" },
      { key: "completion_percentage", label: "Complete %", type: "number" },
      { key: "total_paid", label: "Paid", type: "number" },
      { key: "total_invoiced", label: "Invoiced", type: "number" },
      { key: "remaining_amount", label: "Remaining", type: "number" },
      { key: "status", label: "Status", type: "badge" },
    ],
  },

  financial: {
    key: "financial",
    label: "Financial Overview",
    endpoint: "reports/financial/",
    description: "Executive view of budgets, costs, payroll, contracts, and project exposure",
    filters: [
      { name: "project_id", label: "Project ID", type: "number" },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
    ],
    columns: [
      { key: "project", label: "Project" },
      { key: "budget", label: "Budget", type: "currency" },
      { key: "budget_currency", label: "Budget Cur" },
      { key: "expenses_usd", label: "Expenses USD", type: "currency" },
      { key: "expenses_afn", label: "Expenses AFN", type: "currency" },
      { key: "worker_payroll_usd", label: "Worker Payroll USD", type: "currency" },
      { key: "worker_payroll_afn", label: "Worker Payroll AFN", type: "currency" },
      { key: "contract_value_usd", label: "Contract Value USD", type: "currency" },
      { key: "contract_value_afn", label: "Contract Value AFN", type: "currency" },
      { key: "contract_paid_usd", label: "Contract Paid USD", type: "currency" },
      { key: "contract_paid_afn", label: "Contract Paid AFN", type: "currency" },
      { key: "total_cost_usd", label: "Total USD", type: "currency" },
      { key: "total_cost_afn", label: "Total AFN", type: "currency" },
    ],
  },
};

export const REPORT_LIST = Object.values(REPORTS);
