export const REPORTS = {
  projects: {
    key: "projects",
    label: "Projects",
    icon: "🏗️",
    endpoint: "reports/projects/",
    description: "Project summary with budgets and expenses",
    filters: [
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "", label: "All Statuses" },
          { value: "planning", label: "Planning" },
          { value: "ongoing", label: "Ongoing" },
          { value: "completed", label: "Completed" },
          { value: "on_hold", label: "On Hold" },
        ],
      },
      {
        name: "property_type",
        label: "Property Type",
        type: "select",
        options: [
          { value: "", label: "All Types" },
          { value: "residential", label: "Residential" },
          { value: "commercial", label: "Commercial" },
          { value: "mixed", label: "Mixed Use" },
        ],
      },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
    ],
    columns: [
      { key: "name", label: "Project" },
      { key: "property_type", label: "Type" },
      { key: "location", label: "Location" },
      { key: "status", label: "Status", type: "badge" },
      { key: "estimated_budget", label: "Budget", type: "currency" },
      { key: "budget_currency", label: "Cur" },
      { key: "total_expense_usd", label: "Spent (USD)", type: "currency" },
      { key: "budget_remaining", label: "Remaining", type: "currency" },
    ],
  },

  expenses: {
    key: "expenses",
    label: "Expenses",
    icon: "💰",
    endpoint: "reports/expenses/",
    description: "Detailed expense records and breakdowns",
    filters: [
      { name: "project_id", label: "Project ID", type: "number" },
      {
        name: "expense_type",
        label: "Expense Type",
        type: "select",
        options: [
          { value: "", label: "All Types" },
          { value: "general", label: "General" },
          { value: "material", label: "Material" },
          { value: "construction", label: "Construction" },
          { value: "staff_salary", label: "Staff Salary" },
          { value: "daily_wage", label: "Daily Wage" },
          { value: "contract_payment", label: "Contract Payment" },
          { value: "equipment", label: "Equipment" },
          { value: "utility", label: "Utility" },
          { value: "other", label: "Other" },
        ],
      },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
    ],
    columns: [
      { key: "serial_number", label: "S/N" },
      { key: "project", label: "Project" },
      { key: "expense_date", label: "Date", type: "date" },
      { key: "description", label: "Description" },
      { key: "amount_afn", label: "AFN", type: "number" },
      { key: "amount_usd", label: "USD", type: "number" },
      { key: "total_usd", label: "Total USD", type: "number" },
      { key: "expense_type", label: "Type", type: "badge" },
    ],
  },

  payroll: {
    key: "payroll",
    label: "Payroll",
    icon: "🧾",
    endpoint: "reports/payroll/",
    description: "Employee payroll records",
    filters: [
      { name: "employee_id", label: "Employee ID", type: "number" },
      {
        name: "currency",
        label: "Currency",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "AFN", label: "AFN" },
          { value: "USD", label: "USD" },
        ],
      },
      {
        name: "payment_method",
        label: "Payment Method",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "bank_transfer", label: "Bank Transfer" },
          { value: "check", label: "Check" },
          { value: "cash", label: "Cash" },
        ],
      },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
    ],
    columns: [
      { key: "employee", label: "Employee" },
      { key: "department", label: "Dept" },
      { key: "period_start", label: "From", type: "date" },
      { key: "period_end", label: "To", type: "date" },
      { key: "currency", label: "Cur" },
      { key: "gross_pay", label: "Gross", type: "number" },
      { key: "deductions", label: "Deduct", type: "number" },
      { key: "net_pay", label: "Net", type: "number" },
    ],
  },

  attendance: {
    key: "attendance",
    label: "Attendance",
    icon: "📅",
    endpoint: "reports/attendance/",
    description: "Employee attendance records",
    filters: [
      { name: "employee_id", label: "Employee ID", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "present", label: "Present" },
          { value: "absent", label: "Absent" },
          { value: "half_day", label: "Half Day" },
          { value: "leave", label: "Leave" },
        ],
      },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
    ],
    columns: [
      { key: "employee", label: "Employee" },
      { key: "date", label: "Date", type: "date" },
      { key: "status", label: "Status", type: "badge" },
      { key: "check_in", label: "In" },
      { key: "check_out", label: "Out" },
      { key: "overtime_hours", label: "OT Hrs", type: "number" },
    ],
  },

  employees: {
    key: "employees",
    label: "Employees",
    icon: "👷",
    endpoint: "reports/employees/",
    description: "Employee directory & department breakdown",
    filters: [
      {
        name: "department",
        label: "Department",
        type: "select",
        options: [
          { value: "", label: "All Departments" },
          { value: "management", label: "Management" },
          { value: "engineering", label: "Engineering" },
          { value: "construction", label: "Construction" },
          { value: "administration", label: "Administration" },
          { value: "finance", label: "Finance" },
          { value: "hr", label: "Human Resources" },
          { value: "procurement", label: "Procurement" },
          { value: "safety", label: "Safety" },
        ],
      },
      {
        name: "employment_type",
        label: "Employment Type",
        type: "select",
        options: [
          { value: "", label: "All Types" },
          { value: "full_time", label: "Full Time" },
          { value: "part_time", label: "Part Time" },
          { value: "contract", label: "Contract" },
          { value: "temporary", label: "Temporary" },
        ],
      },
      {
        name: "is_active",
        label: "Active Status",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "true", label: "Active" },
          { value: "false", label: "Inactive" },
        ],
      },
    ],
    columns: [
      { key: "employee_id", label: "ID" },
      { key: "full_name", label: "Name" },
      { key: "department", label: "Dept" },
      { key: "position", label: "Position" },
      { key: "employment_type", label: "Type" },
      { key: "hire_date", label: "Hired", type: "date" },
      { key: "salary", label: "Salary", type: "number" },
      { key: "is_active", label: "Active", type: "bool" },
    ],
  },

  contracts: {
    key: "contracts",
    label: "Contracts",
    icon: "📑",
    endpoint: "reports/contracts/",
    description: "Subcontractor contracts & financials",
    filters: [
      { name: "project_id", label: "Project ID", type: "number" },
      { name: "subcontractor_id", label: "Subcontractor ID", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "draft", label: "Draft" },
          { value: "active", label: "Active" },
          { value: "completed", label: "Completed" },
          { value: "terminated", label: "Terminated" },
          { value: "cancelled", label: "Cancelled" },
        ],
      },
      {
        name: "currency",
        label: "Currency",
        type: "select",
        options: [
          { value: "", label: "All" },
          { value: "AFN", label: "AFN" },
          { value: "USD", label: "USD" },
        ],
      },
    ],
    columns: [
      { key: "contract_number", label: "Contract #" },
      { key: "project", label: "Project" },
      { key: "subcontractor", label: "Subcontractor" },
      { key: "currency", label: "Cur" },
      { key: "contract_value", label: "Value", type: "number" },
      { key: "total_paid", label: "Paid", type: "number" },
      { key: "remaining_amount", label: "Remaining", type: "number" },
      { key: "status", label: "Status", type: "badge" },
    ],
  },

  financial: {
    key: "financial",
    label: "Financial Overview",
    icon: "📊",
    endpoint: "reports/financial/",
    description: "Company-wide financial overview",
    filters: [
      { name: "project_id", label: "Project ID", type: "number" },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
    ],
    columns: [],
  },
};

export const REPORT_LIST = Object.values(REPORTS);
