# Generated by Django 5.2 on 2026-06-17 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(help_text='Serial number as shown on project expense sheet')),
                ('expense_date', models.DateField()),
                ('description', models.TextField(help_text='Details of what the expense was for')),
                ('remarks', models.TextField(blank=True, default='')),
                ('paid_to', models.CharField(blank=True, default='', help_text='Person/company paid', max_length=255)),
                ('amount_afn', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in Afghan Afghani', max_digits=15)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in US Dollars', max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Exchange rate (AFN per 1 USD) on expense date', max_digits=10)),
                ('expense_type', models.CharField(choices=[('general', 'General Expense'), ('material', 'Construction Material'), ('staff_salary', 'Staff Salary'), ('daily_wage', 'Daily Worker Wage'), ('contract_payment', 'Contract/Subcontractor Payment'), ('equipment', 'Equipment Rental/Purchase'), ('utility', 'Utility Bill'), ('other', 'Other')], default='general', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='project.project')),
            ],
            options={
                'ordering': ['project', 'expense_date', 'serial_number'],
                'constraints': [models.UniqueConstraint(fields=('project', 'serial_number'), name='unique_serial_per_project')],
            },
        ),
    ]
