# Generated by Django 5.2 on 2026-06-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='serial_number',
            field=models.PositiveIntegerField(editable=False, help_text='Auto-generated per project'),
        ),
    ]
