# Generated by Django 5.2 on 2026-06-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('general', 'General Expense'), ('material', 'Construction Material'), ('construction', 'Construction'), ('staff_salary', 'Staff Salary'), ('daily_wage', 'Daily Worker Wage'), ('contract_payment', 'Contract/Subcontractor Payment'), ('equipment', 'Equipment Rental/Purchase'), ('utility', 'Utility Bill'), ('other', 'Other')], default='general', max_length=30),
        ),
    ]
