# Generated by Django 5.2 on 2026-07-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_office_expense_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['expense_scope', 'project', 'expense_date', 'serial_number']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='serial_number',
            field=models.PositiveIntegerField(editable=False, help_text='Auto-generated per project or office ledger'),
        ),
    ]
