# Generated by Django 5.2 on 2026-08-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_expense_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('general', 'General Expense'), ('material', 'Construction Material'), ('construction', 'Construction'), ('fuel', 'Fuel'), ('staff_salary', 'Staff Salary'), ('repairing', 'Repairing'), ('food_costs', 'Food Costs'), ('daily_wage', 'Daily Worker Wage'), ('contract_payment', 'Contract/Subcontractor Payment'), ('equipment', 'Equipment Rental/Purchase'), ('utility', 'Utility Bill'), ('other', 'Other'), ('office_rent', 'Office Rent'), ('utilities', 'Utilities'), ('internet', 'Internet'), ('office_supplies', 'Office Supplies'), ('staff_meals', 'Staff Meals'), ('transportation', 'Transportation'), ('fuel', 'Fuel'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('software_subscriptions', 'Software & Subscriptions'), ('salaries', 'Salaries'), ('miscellaneous', 'Miscellaneous')], default='general', max_length=30),
        ),
    ]
