# Generated by Django 5.2 on 2026-06-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='currency',
            field=models.CharField(choices=[('AFN', 'Afghani (AFN)'), ('USD', 'US Dollar (USD)')], default='AFN', max_length=3),
        ),
    ]
