# Generated by Django 5.2 on 2026-08-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0008_employee_project_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='termination_date',
        ),
    ]
